build-job:
  image: shippingdocker/php-composer:7.4
  stage: build
  script:
    - rm composer.lock
    - composer install

test-job1:
  image: php:7.4-cli
  stage: test
  script:
    - php artisan test
    
deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production